-- Create databases
CREATE DATABASE airflow;
CREATE DATABASE metabase;
CREATE DATABASE mlflow;
CREATE DATABASE mlplatform;

-- Grant privileges
GRANT ALL PRIVILEGES ON DATABASE airflow TO mluser;
GRANT ALL PRIVILEGES ON DATABASE metabase TO mluser;
GRANT ALL PRIVILEGES ON DATABASE mlflow TO mluser;
GRANT ALL PRIVILEGES ON DATABASE mlplatform TO mluser;
